# Generated by Django 5.1.3 on 2025-06-25 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurveyprogress',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersurveyprogress',
            name='email_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
