# Generated by Django 5.1.3 on 2025-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0002_usersurveyprogress_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code_entry_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
