# Generated by Django 5.1.3 on 2025-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0004_participant_randomized_group_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wave1_survey_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave2_monitoring_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave2_survey_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
