# Generated by Django 5.1.3 on 2025-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0005_participant_wave1_survey_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wave3_monitor_ready_sent',
            field=models.BooleanField(default=False),
        ),
    ]
