# Generated by Django 5.1.3 on 2025-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0006_participant_wave3_monitor_ready_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wave3_missing_code_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave3_survey_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave3_survey_monitor_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave3_survey_monitor_return_sent',
            field=models.BooleanField(default=False),
        ),
    ]
