# Generated by Django 5.1.3 on 2025-08-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0007_participant_wave3_missing_code_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('exit_screen', 'Exit Screen Content'), ('waiting_screen', 'Waiting Screen Content'), ('consent_form', 'Consent Form Content'), ('eligibility_interest', 'Eligibility Interest Page'), ('home_page', 'Home Page Content')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content that can be edited by researchers')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='intervention_access_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='intervention_access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='intervention_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='intervention_login_count',
            field=models.IntegerField(default=0),
        ),
    ]
