# Generated by Django 5.1.3 on 2025-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0008_content_participant_challenges_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wave3_code_entry_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
