# Generated by Django 5.1.3 on 2025-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0009_participant_wave3_code_entry_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurveyprogress',
            name='timeline_reference_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
