# Generated by Django 5.1.3 on 2025-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0010_usersurveyprogress_timeline_reference_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='challenge_25_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='challenge_25_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='intervention_points',
            field=models.IntegerField(default=0),
        ),
    ]
