# Generated by Django 5.1.3 on 2025-09-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0012_challenge5response_workrelatedchallenge8response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticRelatedChallenge18Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomesticRelatedChallenge21Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('answer5', models.TextField(blank=True, null=True)),
                ('answer6', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeisureRelatedChallenge23Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeisureRelatedChallenge26Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('answer5', models.TextField(blank=True, null=True)),
                ('answer6', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRelatedChallenge13Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRelatedChallenge16Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('answer5', models.TextField(blank=True, null=True)),
                ('answer6', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRelatedChallenge11Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('answer5', models.TextField(blank=True, null=True)),
                ('answer6', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_number', models.IntegerField(help_text='Challenge number (1-35)')),
                ('challenge_name', models.CharField(help_text='Name of the challenge', max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['challenge_number'],
                'unique_together': {('user', 'challenge_number')},
            },
        ),
    ]
