# Generated by Django 5.1.3 on 2025-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0014_participant_address_line1_participant_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dominant_hand',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], help_text='Non-dominant hand for physical activity monitoring', max_length=10, null=True),
        ),
    ]
