# Generated by Django 5.1.3 on 2025-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0015_add_dominant_hand_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='randomization_completed',
            field=models.BooleanField(default=False, help_text='Whether 2-block randomization has been completed'),
        ),
        migrations.AddField(
            model_name='participant',
            name='randomization_pair_id',
            field=models.IntegerField(blank=True, help_text='Pair ID for 2-block randomization (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='randomization_position',
            field=models.IntegerField(blank=True, choices=[(1, 'First in pair'), (2, 'Second in pair')], help_text='Position within the randomization pair', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('exit_screen', 'Exit Screen Content'), ('waiting_screen', 'Waiting Screen Content'), ('consent_form', 'Consent Form Content'), ('eligibility_interest', 'Eligibility Interest Page'), ('home_page', 'Home Page Content'), ('wave1_survey', 'Wave 1 Survey Content'), ('information_16', 'Information 16 - Control Group Message')], max_length=50, unique=True),
        ),
    ]
