# Generated by Django 5.1.3 on 2025-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0016_participant_randomization_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('exit_screen', 'Exit Screen Content'), ('waiting_screen', 'Waiting Screen Content'), ('consent_form', 'Consent Form Content'), ('eligibility_interest', 'Eligibility Interest Page'), ('home_page', 'Home Page Content'), ('wave1_survey', 'Wave 1 Survey Content'), ('wave2_survey', 'Wave 2 Survey Content'), ('information_16', 'Information 16 - Control Group Message')], max_length=50, unique=True),
        ),
    ]
