# Generated by Django 5.1.3 on 2025-11-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0017_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('exit_screen', 'Exit Screen Content'), ('waiting_screen', 'Waiting Screen Content'), ('consent_form', 'Consent Form Content'), ('eligibility_interest', 'Eligibility Interest Page'), ('home_page', 'Home Page Content'), ('wave1_survey', 'Wave 1 Survey Content'), ('wave2_survey', 'Wave 2 Survey Content'), ('wave3_survey', 'Wave 3 Survey Content'), ('information_16', 'Information 16 - Control Group Message'), ('information_20', 'Information 20 - No Wave 2 Physical Activity Monitoring')], max_length=50, unique=True),
        ),
    ]
