# Generated by Django 5.1.3 on 2025-12-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0018_alter_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.AddField(
            model_name='participant',
            name='randomization_email_sent',
            field=models.BooleanField(default=False, help_text='Whether randomization email was sent to this participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='randomization_email_sent_date',
            field=models.DateField(blank=True, help_text='Date when randomization email was sent', null=True),
        ),
    ]
