# Generated by Django 5.1.3 on 2025-12-23 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0019_add_randomization_email_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_number', models.IntegerField(blank=True, help_text='Challenge number if applicable', null=True)),
                ('challenge_name', models.CharField(blank=True, help_text='Name of the challenge', max_length=200, null=True)),
                ('response_type', models.CharField(choices=[('commitment_click', 'Commitment Box Clicked'), ('challenge_completion', 'Challenge Completed'), ('form_submission', 'Form Submission'), ('game_interaction', 'Game Interaction'), ('video_watched', 'Video Watched'), ('other', 'Other')], help_text='Type of response', max_length=50)),
                ('response_data', models.JSONField(default=dict, help_text='Structured response data (answers, selections, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpas.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'challenge_number'], name='testpas_int_user_id_b91fd1_idx'), models.Index(fields=['participant', 'response_type'], name='testpas_int_partici_c4bfdf_idx'), models.Index(fields=['created_at'], name='testpas_int_created_8341be_idx')],
            },
        ),
    ]
