# Generated by Django 5.2.8 on 2026-01-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0020_interventionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
