# Generated by Django 5.2.8 on 2026-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0021_participant_age_participant_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bmi',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='willing_contact',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='willing_monitor',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='willing_no_other_study',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
